# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'

stages:
- stage: test
  jobs:
  - job: test
    displayName: Run tests
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '2.2.301'
    - task: DotNetCoreCLI@2
      displayName: Install packages for Service
      inputs:
        command: restore
        workingDirectory: 'src/JamFactory.Api'



